repos:
  # 1. Check YAML Syntax
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        files: \.(yml|yaml)$
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # 2. Lint Ansible Playbooks, Roles, and Collections
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v25.1.3
    hooks:
      - id: ansible-lint
        files: \.(yml|yaml)$
        name: ansible-lint
        args:
          - "-p"  # Show violations in a single line
        additional_dependencies:
          - ansible-core>=2.13.0
          - ruamel.yaml>=0.17.21
          - rich>=12.0.0

  # 3. Check for Secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0  # Use a compatible version
    hooks:
      - id: detect-secrets
        args:
          - '--baseline'
          - .secrets.baseline

  # 4. Format YAML
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: \.(yml|yaml)$
        name: yamllint
        args:
          - "-c"
          - ".yamllint.yaml"
