---
- hosts: localhost
  become: yes
  gather_facts: yes
  collections:
    - amazon.aws  # ensure the collection is installed: ansible-galaxy collection install amazon.aws
  pre_tasks:
    - name: Gather EC2 metadata
      amazon.aws.ec2_metadata_facts:
      register: ec2_metadata

    - name: Set region fact
      set_fact:
        region: "{{ ansible_ec2_placement_region }}"

    - name: Gather EC2 instance facts
      amazon.aws.ec2_tag_info:
        region: "{{ region }}"
        resource: "{{ ec2_metadata.ansible_facts.ansible_ec2_instance_id }}"
      register: instance_tags

    - name: Debug EC2 Metadata
      debug:
        var: instance_tags

    - name: Set app fact from EC2 tag "ApplicationName"
      set_fact:
        app_name: "{{ instance_tags.tags.ApplicationName | default('bad_name') }}"

  roles:
    - tools
    - ssm_parameters
    - deploy_container
